# Generated by Django 3.1.4 on 2020-12-17 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_auto_20201209_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_likes',
        ),
        migrations.RemoveField(
            model_name='image',
            name='imageuploader_profile',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
