# Generated by Django 3.1.4 on 2020-12-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_auto_20201222_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.IntegerField(default=0),
        ),
    ]
