# Generated by Django 3.1.4 on 2020-12-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_auto_20201223_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
