# Generated by Django 3.1.4 on 2020-12-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0009_auto_20201224_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mobile',
        ),
    ]
