# Generated by Django 3.1.4 on 2020-12-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0013_auto_20201224_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_avatar',
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=False, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(default=False, max_length=10, unique=True),
        ),
    ]
