# Generated by Django 3.1.4 on 2021-01-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0015_auto_20201224_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(upload_to='pictsagram/'),
        ),
    ]
