# Generated by Django 3.1.4 on 2021-01-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0016_auto_20210103_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(upload_to='ProfilePicture/'),
        ),
    ]
