# Generated by Django 3.1.4 on 2021-01-03 05:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmer', '0017_auto_20210103_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_likes',
            field=models.ManyToManyField(blank=True, default=False, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
